// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/st-ember/microtip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBalanceRepo creates a new instance of MockBalanceRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBalanceRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBalanceRepo {
	mock := &MockBalanceRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBalanceRepo is an autogenerated mock type for the BalanceRepo type
type MockBalanceRepo struct {
	mock.Mock
}

type MockBalanceRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBalanceRepo) EXPECT() *MockBalanceRepo_Expecter {
	return &MockBalanceRepo_Expecter{mock: &_m.Mock}
}

// GetBalance provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) GetBalance(ctx context.Context, userID string) (*domain.Balance, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetBalance")
	}

	var r0 *domain.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Balance, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Balance); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBalanceRepo_GetBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBalance'
type MockBalanceRepo_GetBalance_Call struct {
	*mock.Call
}

// GetBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockBalanceRepo_Expecter) GetBalance(ctx interface{}, userID interface{}) *MockBalanceRepo_GetBalance_Call {
	return &MockBalanceRepo_GetBalance_Call{Call: _e.mock.On("GetBalance", ctx, userID)}
}

func (_c *MockBalanceRepo_GetBalance_Call) Run(run func(ctx context.Context, userID string)) *MockBalanceRepo_GetBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_GetBalance_Call) Return(balance *domain.Balance, err error) *MockBalanceRepo_GetBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockBalanceRepo_GetBalance_Call) RunAndReturn(run func(ctx context.Context, userID string) (*domain.Balance, error)) *MockBalanceRepo_GetBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBalance provides a mock function for the type MockBalanceRepo
func (_mock *MockBalanceRepo) SaveBalance(ctx context.Context, balance *domain.Balance) error {
	ret := _mock.Called(ctx, balance)

	if len(ret) == 0 {
		panic("no return value specified for SaveBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Balance) error); ok {
		r0 = returnFunc(ctx, balance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockBalanceRepo_SaveBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBalance'
type MockBalanceRepo_SaveBalance_Call struct {
	*mock.Call
}

// SaveBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - balance *domain.Balance
func (_e *MockBalanceRepo_Expecter) SaveBalance(ctx interface{}, balance interface{}) *MockBalanceRepo_SaveBalance_Call {
	return &MockBalanceRepo_SaveBalance_Call{Call: _e.mock.On("SaveBalance", ctx, balance)}
}

func (_c *MockBalanceRepo_SaveBalance_Call) Run(run func(ctx context.Context, balance *domain.Balance)) *MockBalanceRepo_SaveBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Balance
		if args[1] != nil {
			arg1 = args[1].(*domain.Balance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBalanceRepo_SaveBalance_Call) Return(err error) *MockBalanceRepo_SaveBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockBalanceRepo_SaveBalance_Call) RunAndReturn(run func(ctx context.Context, balance *domain.Balance) error) *MockBalanceRepo_SaveBalance_Call {
	_c.Call.Return(run)
	return _c
}
