// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/st-ember/microtip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLedgerRepo creates a new instance of MockLedgerRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLedgerRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLedgerRepo {
	mock := &MockLedgerRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLedgerRepo is an autogenerated mock type for the LedgerRepo type
type MockLedgerRepo struct {
	mock.Mock
}

type MockLedgerRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLedgerRepo) EXPECT() *MockLedgerRepo_Expecter {
	return &MockLedgerRepo_Expecter{mock: &_m.Mock}
}

// SaveLedgerEntry provides a mock function for the type MockLedgerRepo
func (_mock *MockLedgerRepo) SaveLedgerEntry(ctx context.Context, entry *domain.LedgerEntry) error {
	ret := _mock.Called(ctx, entry)

	if len(ret) == 0 {
		panic("no return value specified for SaveLedgerEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.LedgerEntry) error); ok {
		r0 = returnFunc(ctx, entry)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLedgerRepo_SaveLedgerEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveLedgerEntry'
type MockLedgerRepo_SaveLedgerEntry_Call struct {
	*mock.Call
}

// SaveLedgerEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entry *domain.LedgerEntry
func (_e *MockLedgerRepo_Expecter) SaveLedgerEntry(ctx interface{}, entry interface{}) *MockLedgerRepo_SaveLedgerEntry_Call {
	return &MockLedgerRepo_SaveLedgerEntry_Call{Call: _e.mock.On("SaveLedgerEntry", ctx, entry)}
}

func (_c *MockLedgerRepo_SaveLedgerEntry_Call) Run(run func(ctx context.Context, entry *domain.LedgerEntry)) *MockLedgerRepo_SaveLedgerEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.LedgerEntry
		if args[1] != nil {
			arg1 = args[1].(*domain.LedgerEntry)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockLedgerRepo_SaveLedgerEntry_Call) Return(err error) *MockLedgerRepo_SaveLedgerEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLedgerRepo_SaveLedgerEntry_Call) RunAndReturn(run func(ctx context.Context, entry *domain.LedgerEntry) error) *MockLedgerRepo_SaveLedgerEntry_Call {
	_c.Call.Return(run)
	return _c
}
