// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/st-ember/microtip/internal/app/port/repo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUnitOfWork creates a new instance of MockUnitOfWork. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUnitOfWork(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUnitOfWork {
	mock := &MockUnitOfWork{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUnitOfWork is an autogenerated mock type for the UnitOfWork type
type MockUnitOfWork struct {
	mock.Mock
}

type MockUnitOfWork_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUnitOfWork) EXPECT() *MockUnitOfWork_Expecter {
	return &MockUnitOfWork_Expecter{mock: &_m.Mock}
}

// BalanceRepo provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) BalanceRepo() repo.BalanceRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BalanceRepo")
	}

	var r0 repo.BalanceRepo
	if returnFunc, ok := ret.Get(0).(func() repo.BalanceRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.BalanceRepo)
		}
	}
	return r0
}

// MockUnitOfWork_BalanceRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BalanceRepo'
type MockUnitOfWork_BalanceRepo_Call struct {
	*mock.Call
}

// BalanceRepo is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) BalanceRepo() *MockUnitOfWork_BalanceRepo_Call {
	return &MockUnitOfWork_BalanceRepo_Call{Call: _e.mock.On("BalanceRepo")}
}

func (_c *MockUnitOfWork_BalanceRepo_Call) Run(run func()) *MockUnitOfWork_BalanceRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_BalanceRepo_Call) Return(balanceRepo repo.BalanceRepo) *MockUnitOfWork_BalanceRepo_Call {
	_c.Call.Return(balanceRepo)
	return _c
}

func (_c *MockUnitOfWork_BalanceRepo_Call) RunAndReturn(run func() repo.BalanceRepo) *MockUnitOfWork_BalanceRepo_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Close(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockUnitOfWork_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Close(ctx interface{}) *MockUnitOfWork_Close_Call {
	return &MockUnitOfWork_Close_Call{Call: _e.mock.On("Close", ctx)}
}

func (_c *MockUnitOfWork_Close_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Close_Call) Return(err error) *MockUnitOfWork_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Close_Call) RunAndReturn(run func(ctx context.Context) error) *MockUnitOfWork_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Commit provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Commit(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Commit")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Commit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Commit'
type MockUnitOfWork_Commit_Call struct {
	*mock.Call
}

// Commit is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Commit(ctx interface{}) *MockUnitOfWork_Commit_Call {
	return &MockUnitOfWork_Commit_Call{Call: _e.mock.On("Commit", ctx)}
}

func (_c *MockUnitOfWork_Commit_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Commit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) Return(err error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Commit_Call) RunAndReturn(run func(ctx context.Context) error) *MockUnitOfWork_Commit_Call {
	_c.Call.Return(run)
	return _c
}

// LedgerRepo provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) LedgerRepo() repo.LedgerRepo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for LedgerRepo")
	}

	var r0 repo.LedgerRepo
	if returnFunc, ok := ret.Get(0).(func() repo.LedgerRepo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(repo.LedgerRepo)
		}
	}
	return r0
}

// MockUnitOfWork_LedgerRepo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LedgerRepo'
type MockUnitOfWork_LedgerRepo_Call struct {
	*mock.Call
}

// LedgerRepo is a helper method to define mock.On call
func (_e *MockUnitOfWork_Expecter) LedgerRepo() *MockUnitOfWork_LedgerRepo_Call {
	return &MockUnitOfWork_LedgerRepo_Call{Call: _e.mock.On("LedgerRepo")}
}

func (_c *MockUnitOfWork_LedgerRepo_Call) Run(run func()) *MockUnitOfWork_LedgerRepo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUnitOfWork_LedgerRepo_Call) Return(ledgerRepo repo.LedgerRepo) *MockUnitOfWork_LedgerRepo_Call {
	_c.Call.Return(ledgerRepo)
	return _c
}

func (_c *MockUnitOfWork_LedgerRepo_Call) RunAndReturn(run func() repo.LedgerRepo) *MockUnitOfWork_LedgerRepo_Call {
	_c.Call.Return(run)
	return _c
}

// Rollback provides a mock function for the type MockUnitOfWork
func (_mock *MockUnitOfWork) Rollback(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Rollback")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUnitOfWork_Rollback_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rollback'
type MockUnitOfWork_Rollback_Call struct {
	*mock.Call
}

// Rollback is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockUnitOfWork_Expecter) Rollback(ctx interface{}) *MockUnitOfWork_Rollback_Call {
	return &MockUnitOfWork_Rollback_Call{Call: _e.mock.On("Rollback", ctx)}
}

func (_c *MockUnitOfWork_Rollback_Call) Run(run func(ctx context.Context)) *MockUnitOfWork_Rollback_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) Return(err error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUnitOfWork_Rollback_Call) RunAndReturn(run func(ctx context.Context) error) *MockUnitOfWork_Rollback_Call {
	_c.Call.Return(run)
	return _c
}
