// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockHasher creates a new instance of MockHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHasher {
	mock := &MockHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHasher is an autogenerated mock type for the Hasher type
type MockHasher struct {
	mock.Mock
}

type MockHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHasher) EXPECT() *MockHasher_Expecter {
	return &MockHasher_Expecter{mock: &_m.Mock}
}

// GenerateCheckMacVal provides a mock function for the type MockHasher
func (_mock *MockHasher) GenerateCheckMacVal(params map[string]string) (string, error) {
	ret := _mock.Called(params)

	if len(ret) == 0 {
		panic("no return value specified for GenerateCheckMacVal")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(map[string]string) (string, error)); ok {
		return returnFunc(params)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]string) string); ok {
		r0 = returnFunc(params)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]string) error); ok {
		r1 = returnFunc(params)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_GenerateCheckMacVal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateCheckMacVal'
type MockHasher_GenerateCheckMacVal_Call struct {
	*mock.Call
}

// GenerateCheckMacVal is a helper method to define mock.On call
//   - params map[string]string
func (_e *MockHasher_Expecter) GenerateCheckMacVal(params interface{}) *MockHasher_GenerateCheckMacVal_Call {
	return &MockHasher_GenerateCheckMacVal_Call{Call: _e.mock.On("GenerateCheckMacVal", params)}
}

func (_c *MockHasher_GenerateCheckMacVal_Call) Run(run func(params map[string]string)) *MockHasher_GenerateCheckMacVal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHasher_GenerateCheckMacVal_Call) Return(s string, err error) *MockHasher_GenerateCheckMacVal_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockHasher_GenerateCheckMacVal_Call) RunAndReturn(run func(params map[string]string) (string, error)) *MockHasher_GenerateCheckMacVal_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateCheckMacVal provides a mock function for the type MockHasher
func (_mock *MockHasher) ValidateCheckMacVal(params map[string]string, incomingMAC string) (bool, error) {
	ret := _mock.Called(params, incomingMAC)

	if len(ret) == 0 {
		panic("no return value specified for ValidateCheckMacVal")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(map[string]string, string) (bool, error)); ok {
		return returnFunc(params, incomingMAC)
	}
	if returnFunc, ok := ret.Get(0).(func(map[string]string, string) bool); ok {
		r0 = returnFunc(params, incomingMAC)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(map[string]string, string) error); ok {
		r1 = returnFunc(params, incomingMAC)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHasher_ValidateCheckMacVal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateCheckMacVal'
type MockHasher_ValidateCheckMacVal_Call struct {
	*mock.Call
}

// ValidateCheckMacVal is a helper method to define mock.On call
//   - params map[string]string
//   - incomingMAC string
func (_e *MockHasher_Expecter) ValidateCheckMacVal(params interface{}, incomingMAC interface{}) *MockHasher_ValidateCheckMacVal_Call {
	return &MockHasher_ValidateCheckMacVal_Call{Call: _e.mock.On("ValidateCheckMacVal", params, incomingMAC)}
}

func (_c *MockHasher_ValidateCheckMacVal_Call) Run(run func(params map[string]string, incomingMAC string)) *MockHasher_ValidateCheckMacVal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 map[string]string
		if args[0] != nil {
			arg0 = args[0].(map[string]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHasher_ValidateCheckMacVal_Call) Return(b bool, err error) *MockHasher_ValidateCheckMacVal_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockHasher_ValidateCheckMacVal_Call) RunAndReturn(run func(params map[string]string, incomingMAC string) (bool, error)) *MockHasher_ValidateCheckMacVal_Call {
	_c.Call.Return(run)
	return _c
}
