// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockLogger creates a new instance of MockLogger. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLogger(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLogger {
	mock := &MockLogger{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLogger is an autogenerated mock type for the Logger type
type MockLogger struct {
	mock.Mock
}

type MockLogger_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLogger) EXPECT() *MockLogger_Expecter {
	return &MockLogger_Expecter{mock: &_m.Mock}
}

// CriticalCtx provides a mock function for the type MockLogger
func (_mock *MockLogger) CriticalCtx(ctx context.Context, msg string, err error, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(ctx, msg, err, keysAndValues)
	} else {
		_mock.Called(ctx, msg, err)
	}

	return
}

// MockLogger_CriticalCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CriticalCtx'
type MockLogger_CriticalCtx_Call struct {
	*mock.Call
}

// CriticalCtx is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - err error
//   - keysAndValues ...any
func (_e *MockLogger_Expecter) CriticalCtx(ctx interface{}, msg interface{}, err interface{}, keysAndValues ...interface{}) *MockLogger_CriticalCtx_Call {
	return &MockLogger_CriticalCtx_Call{Call: _e.mock.On("CriticalCtx",
		append([]interface{}{ctx, msg, err}, keysAndValues...)...)}
}

func (_c *MockLogger_CriticalCtx_Call) Run(run func(ctx context.Context, msg string, err error, keysAndValues ...any)) *MockLogger_CriticalCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_CriticalCtx_Call) Return() *MockLogger_CriticalCtx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_CriticalCtx_Call) RunAndReturn(run func(ctx context.Context, msg string, err error, keysAndValues ...any)) *MockLogger_CriticalCtx_Call {
	_c.Run(run)
	return _c
}

// ErrorCtx provides a mock function for the type MockLogger
func (_mock *MockLogger) ErrorCtx(ctx context.Context, msg string, err error, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(ctx, msg, err, keysAndValues)
	} else {
		_mock.Called(ctx, msg, err)
	}

	return
}

// MockLogger_ErrorCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ErrorCtx'
type MockLogger_ErrorCtx_Call struct {
	*mock.Call
}

// ErrorCtx is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - err error
//   - keysAndValues ...any
func (_e *MockLogger_Expecter) ErrorCtx(ctx interface{}, msg interface{}, err interface{}, keysAndValues ...interface{}) *MockLogger_ErrorCtx_Call {
	return &MockLogger_ErrorCtx_Call{Call: _e.mock.On("ErrorCtx",
		append([]interface{}{ctx, msg, err}, keysAndValues...)...)}
}

func (_c *MockLogger_ErrorCtx_Call) Run(run func(ctx context.Context, msg string, err error, keysAndValues ...any)) *MockLogger_ErrorCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 error
		if args[2] != nil {
			arg2 = args[2].(error)
		}
		var arg3 []any
		var variadicArgs []any
		if len(args) > 3 {
			variadicArgs = args[3].([]any)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockLogger_ErrorCtx_Call) Return() *MockLogger_ErrorCtx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_ErrorCtx_Call) RunAndReturn(run func(ctx context.Context, msg string, err error, keysAndValues ...any)) *MockLogger_ErrorCtx_Call {
	_c.Run(run)
	return _c
}

// InfoCtx provides a mock function for the type MockLogger
func (_mock *MockLogger) InfoCtx(ctx context.Context, msg string, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(ctx, msg, keysAndValues)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_InfoCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InfoCtx'
type MockLogger_InfoCtx_Call struct {
	*mock.Call
}

// InfoCtx is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - keysAndValues ...any
func (_e *MockLogger_Expecter) InfoCtx(ctx interface{}, msg interface{}, keysAndValues ...interface{}) *MockLogger_InfoCtx_Call {
	return &MockLogger_InfoCtx_Call{Call: _e.mock.On("InfoCtx",
		append([]interface{}{ctx, msg}, keysAndValues...)...)}
}

func (_c *MockLogger_InfoCtx_Call) Run(run func(ctx context.Context, msg string, keysAndValues ...any)) *MockLogger_InfoCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_InfoCtx_Call) Return() *MockLogger_InfoCtx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_InfoCtx_Call) RunAndReturn(run func(ctx context.Context, msg string, keysAndValues ...any)) *MockLogger_InfoCtx_Call {
	_c.Run(run)
	return _c
}

// WarnCtx provides a mock function for the type MockLogger
func (_mock *MockLogger) WarnCtx(ctx context.Context, msg string, keysAndValues ...any) {
	if len(keysAndValues) > 0 {
		_mock.Called(ctx, msg, keysAndValues)
	} else {
		_mock.Called(ctx, msg)
	}

	return
}

// MockLogger_WarnCtx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WarnCtx'
type MockLogger_WarnCtx_Call struct {
	*mock.Call
}

// WarnCtx is a helper method to define mock.On call
//   - ctx context.Context
//   - msg string
//   - keysAndValues ...any
func (_e *MockLogger_Expecter) WarnCtx(ctx interface{}, msg interface{}, keysAndValues ...interface{}) *MockLogger_WarnCtx_Call {
	return &MockLogger_WarnCtx_Call{Call: _e.mock.On("WarnCtx",
		append([]interface{}{ctx, msg}, keysAndValues...)...)}
}

func (_c *MockLogger_WarnCtx_Call) Run(run func(ctx context.Context, msg string, keysAndValues ...any)) *MockLogger_WarnCtx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockLogger_WarnCtx_Call) Return() *MockLogger_WarnCtx_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockLogger_WarnCtx_Call) RunAndReturn(run func(ctx context.Context, msg string, keysAndValues ...any)) *MockLogger_WarnCtx_Call {
	_c.Run(run)
	return _c
}
