// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/st-ember/microtip/internal/app/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCheckoutUsecase creates a new instance of MockCheckoutUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCheckoutUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCheckoutUsecase {
	mock := &MockCheckoutUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCheckoutUsecase is an autogenerated mock type for the CheckoutUsecase type
type MockCheckoutUsecase struct {
	mock.Mock
}

type MockCheckoutUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCheckoutUsecase) EXPECT() *MockCheckoutUsecase_Expecter {
	return &MockCheckoutUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockCheckoutUsecase
func (_mock *MockCheckoutUsecase) Execute(ctx context.Context, userID string, totalAmount int64) (*usecase.CheckoutResult, error) {
	ret := _mock.Called(ctx, userID, totalAmount)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 *usecase.CheckoutResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) (*usecase.CheckoutResult, error)); ok {
		return returnFunc(ctx, userID, totalAmount)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int64) *usecase.CheckoutResult); ok {
		r0 = returnFunc(ctx, userID, totalAmount)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*usecase.CheckoutResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int64) error); ok {
		r1 = returnFunc(ctx, userID, totalAmount)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCheckoutUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockCheckoutUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
//   - totalAmount int64
func (_e *MockCheckoutUsecase_Expecter) Execute(ctx interface{}, userID interface{}, totalAmount interface{}) *MockCheckoutUsecase_Execute_Call {
	return &MockCheckoutUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, userID, totalAmount)}
}

func (_c *MockCheckoutUsecase_Execute_Call) Run(run func(ctx context.Context, userID string, totalAmount int64)) *MockCheckoutUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCheckoutUsecase_Execute_Call) Return(checkoutResult *usecase.CheckoutResult, err error) *MockCheckoutUsecase_Execute_Call {
	_c.Call.Return(checkoutResult, err)
	return _c
}

func (_c *MockCheckoutUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, userID string, totalAmount int64) (*usecase.CheckoutResult, error)) *MockCheckoutUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
