// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/st-ember/microtip/internal/app/usecase"
	mock "github.com/stretchr/testify/mock"
)

// NewMockConfirmationUsecase creates a new instance of MockConfirmationUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfirmationUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfirmationUsecase {
	mock := &MockConfirmationUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockConfirmationUsecase is an autogenerated mock type for the ConfirmationUsecase type
type MockConfirmationUsecase struct {
	mock.Mock
}

type MockConfirmationUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfirmationUsecase) EXPECT() *MockConfirmationUsecase_Expecter {
	return &MockConfirmationUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockConfirmationUsecase
func (_mock *MockConfirmationUsecase) Execute(ctx context.Context, input usecase.ConfirmationInput) error {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, usecase.ConfirmationInput) error); ok {
		r0 = returnFunc(ctx, input)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockConfirmationUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockConfirmationUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - input usecase.ConfirmationInput
func (_e *MockConfirmationUsecase_Expecter) Execute(ctx interface{}, input interface{}) *MockConfirmationUsecase_Execute_Call {
	return &MockConfirmationUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, input)}
}

func (_c *MockConfirmationUsecase_Execute_Call) Run(run func(ctx context.Context, input usecase.ConfirmationInput)) *MockConfirmationUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 usecase.ConfirmationInput
		if args[1] != nil {
			arg1 = args[1].(usecase.ConfirmationInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockConfirmationUsecase_Execute_Call) Return(err error) *MockConfirmationUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockConfirmationUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, input usecase.ConfirmationInput) error) *MockConfirmationUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
