// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockFailTopupUsecase creates a new instance of MockFailTopupUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFailTopupUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFailTopupUsecase {
	mock := &MockFailTopupUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFailTopupUsecase is an autogenerated mock type for the FailTopupUsecase type
type MockFailTopupUsecase struct {
	mock.Mock
}

type MockFailTopupUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFailTopupUsecase) EXPECT() *MockFailTopupUsecase_Expecter {
	return &MockFailTopupUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockFailTopupUsecase
func (_mock *MockFailTopupUsecase) Execute(ctx context.Context, merchantTradeNo string) error {
	ret := _mock.Called(ctx, merchantTradeNo)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, merchantTradeNo)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFailTopupUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockFailTopupUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - merchantTradeNo string
func (_e *MockFailTopupUsecase_Expecter) Execute(ctx interface{}, merchantTradeNo interface{}) *MockFailTopupUsecase_Execute_Call {
	return &MockFailTopupUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, merchantTradeNo)}
}

func (_c *MockFailTopupUsecase_Execute_Call) Run(run func(ctx context.Context, merchantTradeNo string)) *MockFailTopupUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFailTopupUsecase_Execute_Call) Return(err error) *MockFailTopupUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFailTopupUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, merchantTradeNo string) error) *MockFailTopupUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
