// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/st-ember/microtip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStatusCheckUsecase creates a new instance of MockStatusCheckUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStatusCheckUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStatusCheckUsecase {
	mock := &MockStatusCheckUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStatusCheckUsecase is an autogenerated mock type for the StatusCheckUsecase type
type MockStatusCheckUsecase struct {
	mock.Mock
}

type MockStatusCheckUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStatusCheckUsecase) EXPECT() *MockStatusCheckUsecase_Expecter {
	return &MockStatusCheckUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockStatusCheckUsecase
func (_mock *MockStatusCheckUsecase) Execute(ctx context.Context, tradeNo string) (domain.OrderStatus, error) {
	ret := _mock.Called(ctx, tradeNo)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 domain.OrderStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.OrderStatus, error)); ok {
		return returnFunc(ctx, tradeNo)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.OrderStatus); ok {
		r0 = returnFunc(ctx, tradeNo)
	} else {
		r0 = ret.Get(0).(domain.OrderStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, tradeNo)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStatusCheckUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockStatusCheckUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - tradeNo string
func (_e *MockStatusCheckUsecase_Expecter) Execute(ctx interface{}, tradeNo interface{}) *MockStatusCheckUsecase_Execute_Call {
	return &MockStatusCheckUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, tradeNo)}
}

func (_c *MockStatusCheckUsecase_Execute_Call) Run(run func(ctx context.Context, tradeNo string)) *MockStatusCheckUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStatusCheckUsecase_Execute_Call) Return(orderStatus domain.OrderStatus, err error) *MockStatusCheckUsecase_Execute_Call {
	_c.Call.Return(orderStatus, err)
	return _c
}

func (_c *MockStatusCheckUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, tradeNo string) (domain.OrderStatus, error)) *MockStatusCheckUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
