// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/st-ember/microtip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockTipTransferUsecase creates a new instance of MockTipTransferUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTipTransferUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTipTransferUsecase {
	mock := &MockTipTransferUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockTipTransferUsecase is an autogenerated mock type for the TipTransferUsecase type
type MockTipTransferUsecase struct {
	mock.Mock
}

type MockTipTransferUsecase_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTipTransferUsecase) EXPECT() *MockTipTransferUsecase_Expecter {
	return &MockTipTransferUsecase_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function for the type MockTipTransferUsecase
func (_mock *MockTipTransferUsecase) Execute(ctx context.Context, cmd *domain.TipTransferCommand) error {
	ret := _mock.Called(ctx, cmd)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.TipTransferCommand) error); ok {
		r0 = returnFunc(ctx, cmd)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockTipTransferUsecase_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockTipTransferUsecase_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - cmd *domain.TipTransferCommand
func (_e *MockTipTransferUsecase_Expecter) Execute(ctx interface{}, cmd interface{}) *MockTipTransferUsecase_Execute_Call {
	return &MockTipTransferUsecase_Execute_Call{Call: _e.mock.On("Execute", ctx, cmd)}
}

func (_c *MockTipTransferUsecase_Execute_Call) Run(run func(ctx context.Context, cmd *domain.TipTransferCommand)) *MockTipTransferUsecase_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.TipTransferCommand
		if args[1] != nil {
			arg1 = args[1].(*domain.TipTransferCommand)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockTipTransferUsecase_Execute_Call) Return(err error) *MockTipTransferUsecase_Execute_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockTipTransferUsecase_Execute_Call) RunAndReturn(run func(ctx context.Context, cmd *domain.TipTransferCommand) error) *MockTipTransferUsecase_Execute_Call {
	_c.Call.Return(run)
	return _c
}
