// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/st-ember/microtip/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// InvalidateKey provides a mock function for the type MockCache
func (_mock *MockCache) InvalidateKey(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_InvalidateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateKey'
type MockCache_InvalidateKey_Call struct {
	*mock.Call
}

// InvalidateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter) InvalidateKey(ctx interface{}, key interface{}) *MockCache_InvalidateKey_Call {
	return &MockCache_InvalidateKey_Call{Call: _e.mock.On("InvalidateKey", ctx, key)}
}

func (_c *MockCache_InvalidateKey_Call) Run(run func(ctx context.Context, key string)) *MockCache_InvalidateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_InvalidateKey_Call) Return(err error) *MockCache_InvalidateKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_InvalidateKey_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockCache_InvalidateKey_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBalance provides a mock function for the type MockCache
func (_mock *MockCache) ReadBalance(ctx context.Context, key string) (*domain.Balance, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ReadBalance")
	}

	var r0 *domain.Balance
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Balance, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Balance); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Balance)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_ReadBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBalance'
type MockCache_ReadBalance_Call struct {
	*mock.Call
}

// ReadBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter) ReadBalance(ctx interface{}, key interface{}) *MockCache_ReadBalance_Call {
	return &MockCache_ReadBalance_Call{Call: _e.mock.On("ReadBalance", ctx, key)}
}

func (_c *MockCache_ReadBalance_Call) Run(run func(ctx context.Context, key string)) *MockCache_ReadBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_ReadBalance_Call) Return(balance *domain.Balance, err error) *MockCache_ReadBalance_Call {
	_c.Call.Return(balance, err)
	return _c
}

func (_c *MockCache_ReadBalance_Call) RunAndReturn(run func(ctx context.Context, key string) (*domain.Balance, error)) *MockCache_ReadBalance_Call {
	_c.Call.Return(run)
	return _c
}

// ReadOrder provides a mock function for the type MockCache
func (_mock *MockCache) ReadOrder(ctx context.Context, key string) (*domain.Order, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for ReadOrder")
	}

	var r0 *domain.Order
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.Order, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.Order); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Order)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCache_ReadOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadOrder'
type MockCache_ReadOrder_Call struct {
	*mock.Call
}

// ReadOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockCache_Expecter) ReadOrder(ctx interface{}, key interface{}) *MockCache_ReadOrder_Call {
	return &MockCache_ReadOrder_Call{Call: _e.mock.On("ReadOrder", ctx, key)}
}

func (_c *MockCache_ReadOrder_Call) Run(run func(ctx context.Context, key string)) *MockCache_ReadOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_ReadOrder_Call) Return(order *domain.Order, err error) *MockCache_ReadOrder_Call {
	_c.Call.Return(order, err)
	return _c
}

func (_c *MockCache_ReadOrder_Call) RunAndReturn(run func(ctx context.Context, key string) (*domain.Order, error)) *MockCache_ReadOrder_Call {
	_c.Call.Return(run)
	return _c
}

// SaveBalance provides a mock function for the type MockCache
func (_mock *MockCache) SaveBalance(ctx context.Context, balance *domain.Balance) error {
	ret := _mock.Called(ctx, balance)

	if len(ret) == 0 {
		panic("no return value specified for SaveBalance")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Balance) error); ok {
		r0 = returnFunc(ctx, balance)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SaveBalance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveBalance'
type MockCache_SaveBalance_Call struct {
	*mock.Call
}

// SaveBalance is a helper method to define mock.On call
//   - ctx context.Context
//   - balance *domain.Balance
func (_e *MockCache_Expecter) SaveBalance(ctx interface{}, balance interface{}) *MockCache_SaveBalance_Call {
	return &MockCache_SaveBalance_Call{Call: _e.mock.On("SaveBalance", ctx, balance)}
}

func (_c *MockCache_SaveBalance_Call) Run(run func(ctx context.Context, balance *domain.Balance)) *MockCache_SaveBalance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Balance
		if args[1] != nil {
			arg1 = args[1].(*domain.Balance)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_SaveBalance_Call) Return(err error) *MockCache_SaveBalance_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SaveBalance_Call) RunAndReturn(run func(ctx context.Context, balance *domain.Balance) error) *MockCache_SaveBalance_Call {
	_c.Call.Return(run)
	return _c
}

// SaveOrder provides a mock function for the type MockCache
func (_mock *MockCache) SaveOrder(ctx context.Context, order *domain.Order) error {
	ret := _mock.Called(ctx, order)

	if len(ret) == 0 {
		panic("no return value specified for SaveOrder")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Order) error); ok {
		r0 = returnFunc(ctx, order)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCache_SaveOrder_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SaveOrder'
type MockCache_SaveOrder_Call struct {
	*mock.Call
}

// SaveOrder is a helper method to define mock.On call
//   - ctx context.Context
//   - order *domain.Order
func (_e *MockCache_Expecter) SaveOrder(ctx interface{}, order interface{}) *MockCache_SaveOrder_Call {
	return &MockCache_SaveOrder_Call{Call: _e.mock.On("SaveOrder", ctx, order)}
}

func (_c *MockCache_SaveOrder_Call) Run(run func(ctx context.Context, order *domain.Order)) *MockCache_SaveOrder_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Order
		if args[1] != nil {
			arg1 = args[1].(*domain.Order)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockCache_SaveOrder_Call) Return(err error) *MockCache_SaveOrder_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCache_SaveOrder_Call) RunAndReturn(run func(ctx context.Context, order *domain.Order) error) *MockCache_SaveOrder_Call {
	_c.Call.Return(run)
	return _c
}
